# https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
.tolerate-control-plane: &tolerate-control-plane
  key: "CriticalAddonsOnly"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"

controller:
  terminationGracePeriodSeconds: 30
  tolerations:
  - <<: *tolerate-control-plane

  admissionWebhooks:
    patch:
      tolerations:
      - <<: *tolerate-control-plane
  config:
    enable-modsecurity: "true"
    enable-owasp-modsecurity-crs: "true"
    modsecurity-snippet: |
      SecAuditLogType Serial
      SecAuditLog /dev/stdout
      SecAuditLogFormat JSON
      SecAuditEngine RelevantOnly
    ssl-protocols: "TLSv1.2"
    ssl-ciphers: "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256"
    use-gzip: "true"
    block-user-agents: "~*semrush,~*ahrefs,~*mj12bot,~*petalbot,~*dotbot,~*yandex,~*bingbot,~*gptbot,~*chatgpt-user,~*claudebot,~*bytespider,~*amazonbot,~*HTTrack,~*nikto"
  extraArgs:
    enable-ssl-passthrough: true

  name: controller-external

  hostname: nginx-external-lb
  ingressClass: nginx-external
  electionID: nginx-external-leader
  ingressClassResource:
    name: nginx-external
    enabled: true
    default: false
    controllerValue: "k8s.io/ingress-nginx-external"

  service:
    annotations:
      metallb.io/loadBalancerIPs: "192.168.1.220"
    external:
      enabled: true

