# https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
.tolerate-control-plane: &tolerate-control-plane
  key: "CriticalAddonsOnly"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"

controller:
  terminationGracePeriodSeconds: 30
  tolerations:
  - <<: *tolerate-control-plane

  admissionWebhooks:
    patch:
      tolerations:
      - <<: *tolerate-control-plane
  config:
    use-proxy-protocol: "true"
    enable-modsecurity: "true"
    enable-owasp-modsecurity-crs: "true"
  extraArgs:
    enable-ssl-passthrough: true

  name: controller-external

  podAnnotations:
    fluentbit.io/parser_stdout: "k8s-nginx-ingress-stdout"
    fluentbit.io/parser_stderr: "k8s-ingress-nginx-stderr"

  hostname: nginx-external-lb
  ingressClass: nginx-external
  electionID: nginx-external-leader
  ingressClassResource:
    name: nginx-external
    enabled: true
    default: false
    controllerValue: "k8s.io/ingress-nginx-external"

  service:
    loadBalancerIP: 192.168.1.220
    external:
      enabled: true

  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
      namespace: obs
