# https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
.tolerate-control-plane: &tolerate-control-plane
  key: "CriticalAddonsOnly"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"

controller:
  terminationGracePeriodSeconds: 30
  tolerations:
  - <<: *tolerate-control-plane

  admissionWebhooks:
    patch:
      tolerations:
      - <<: *tolerate-control-plane
  config:
    use-proxy-protocol: "true"
    enable-modsecurity: "true"
    enable-owasp-modsecurity-crs: "true"
    use-gzip: "true"
    block-user-agents: "~*bot,~*crawler,~*spider,~*scraper,~*archiver,~*wget,~*curl,~*httpie,~*python-requests,~*Go-http-client,~*java,~*libwww,~*lwp-trivial,~*HTTrack,~*clshttp,~*cmsworldmap,~*comodo,~*diavol,~*dotbot,~*feedfinder,~*flicky,~*ia_archiver,~*kmccrew,~*nutch,~*planetwork,~*purebot,~*pycurl,~*nikto,~*semrush,~*ahrefs,~*mj12bot,~*petalbot,~*yandex,~*bingbot,~*gptbot,~*chatgpt,~*claudebot,~*anthropic,~*bytespider,~*amazonbot"
    limit-req-status-code: "429"
    limit-conn-status-code: "429"
  extraArgs:
    enable-ssl-passthrough: true

  name: controller-external

  hostname: nginx-external-lb
  ingressClass: nginx-external
  electionID: nginx-external-leader
  ingressClassResource:
    name: nginx-external
    enabled: true
    default: false
    controllerValue: "k8s.io/ingress-nginx-external"

  service:
    annotations:
      metallb.io/loadBalancerIPs: "192.168.1.220"
    external:
      enabled: true

