# https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
.tolerate-control-plane: &tolerate-control-plane
  key: "CriticalAddonsOnly"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"

controller:
  tolerations:
  - <<: *tolerate-control-plane

  admissionWebhooks:
    patch:
      tolerations:
      - <<: *tolerate-control-plane

  name: controller-external

  podAnnotations:
    fluentbit.io/parser_stdout: "k8s-nginx-ingress-stdout"
    fluentbit.io/parser_stderr: "k8s-ingress-nginx-stderr"

  hostname: nginx-external-lb
  ingressClass: nginx-external
  ingressClassResource:
    name: nginx-external
    enabled: true
    default: false
    controllerValue: "k8s.io/ingress-nginx-external"

  service:
    external:
      enabled: true
      loadBalancerIP: 192.168.1.220

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: obs
