---
default_user: rocky
sudo_group: wheel
ansible_user: macgregor
ssh_pub_key: /home/mstratto/.ssh/macgregor.id_rsa.pub
systemd_dir: /etc/systemd/system
k3s_version: v1.27.2+k3s1
k3s_server_location: /var/lib/rancher/k3s
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--disable coredns --disable traefik --disable servicelb --disable-cloud-controller --write-kubeconfig-mode 644 --node-taint CriticalAddonsOnly=true:NoSchedule --datastore-endpoint mysql://kubernetes:{{lookup('env', 'KUBE_MYSQL_PASSWORD')}}@tcp(192.168.1.200:3306)/kubernetes --token {{lookup('env', 'KUBE_SERVER_TOKEN')}} --kubelet-arg=image-gc-high-threshold=70 --kubelet-arg=image-gc-low-threshold=50"
extra_agent_args: "--token {{lookup('env', 'KUBE_SERVER_TOKEN')}} --kubelet-arg=image-gc-high-threshold=70 --kubelet-arg=image-gc-low-threshold=50"
gmail_email_address: "{{lookup('env', 'GMAIL_EMAIL_ADDRESS')}}"
gmail_app_password: "{{lookup('env', 'GMAIL_APP_PASSWORD')}}"