---
k3s_version: v1.23.5+k3s1
ssh_pub_key: /Users/mstratto/.ssh/macgregor.id_rsa.pub
ansible_user: macgregor
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--disable traefik --disable servicelb --write-kubeconfig-mode 644 --node-taint CriticalAddonsOnly=true:NoSchedule --datastore-endpoint mysql://kubernetes:{{lookup('env', 'KUBE_MYSQL_PASSWORD')}}@tcp(192.168.1.200:3306)/kubernetes --token {{lookup('env', 'KUBE_SERVER_TOKEN')}}"
extra_agent_args: ""
