---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    app.kubernetes.io/instance: synology-csi
    app.kubernetes.io/name: synology-csi
    app.kubernetes.io/version: 1.0.1
  name: synology-csi-system-data-retain
provisioner: csi.san.synology.com
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  location: /volume2
  type: thin
  fsType: ext4
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    app.kubernetes.io/instance: synology-csi
    app.kubernetes.io/name: synology-csi
    app.kubernetes.io/version: 1.0.1
  name: synology-csi-system-data-delete
provisioner: csi.san.synology.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  location: /volume2
  type: thin
  fsType: ext4
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    app.kubernetes.io/instance: synology-csi
    app.kubernetes.io/name: synology-csi
    app.kubernetes.io/version: 1.0.1
  name: synology-csi-app-data-retain
provisioner: csi.san.synology.com
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  location: /volume3
  type: thin
  fsType: ext4
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    app.kubernetes.io/instance: synology-csi
    app.kubernetes.io/name: synology-csi
    app.kubernetes.io/version: 1.0.1
  name: synology-csi-app-data-delete
provisioner: csi.san.synology.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  location: /volume3
  type: thin
  fsType: ext4
