---
- name: Deploy systemd unit files
  ansible.builtin.template:
    src: k3s.service
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: 0644
  notify: 
    - reload-systemd
    - restart-k3s

- name: Enable and check K3s service
  #tags: [ slow ]
  systemd:
    name: k3s
    daemon_reload: yes
    state: "started"
    enabled: yes
  notify: restart-k3s

- name: Wait for agent-token
  wait_for:
    path: "/var/lib/rancher/k3s/server/agent-token"

- name: Read agent-token from master
  slurp:
    path: "/var/lib/rancher/k3s/server/agent-token"
  register: agent_token

- name: Store Master node-token
  set_fact:
    agent_token: "{{ agent_token.content }}"

- name: Copy config file to user home directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: "u=rw,g=,o="

- name: Replace https://localhost:6443 to https://{{ master_hostname }}:6443
  command: >-
    /usr/local/bin/k3s kubectl config set-cluster default
      --server=https://{{ master_hostname }}:6443
      --kubeconfig ~{{ ansible_user }}/.kube/config
  changed_when: true
