# https://github.com/helm/charts/tree/master/stable/metallb
configInline:
  address-pools:
   - name: default
     protocol: layer2
     addresses:
     - 192.168.1.220-192.168.1.229

prometheus:
  serviceMonitor:
    enabled: true
