# https://artifacthub.io/packages/helm/metallb/metallb
# https://metallb.universe.tf/
.tolerate-control-plane: &tolerate-control-plane
  key: "CriticalAddonsOnly"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"

.node-affinity-prefer-control-plane: &node-affinity-prefer-control-plane
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: In
          values:
          - 'true'

controller:
  tolerations:
    - <<: *tolerate-control-plane
  affinity:
    <<: *node-affinity-prefer-control-plane
  resources:
    requests:
      cpu: 10m
      memory: 64Mi

speaker:
  tolerations:
    - <<: *tolerate-control-plane
  frr:
    enabled: false
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
