repositories:
- name: bitnami 
  url: https://charts.bitnami.com/bitnami
helmDefaults:
  createNamespace: true
releases:
- name: metallb
  chart: bitnami/metallb
  namespace: metallb
  values:
  - ./helm-values.yml
