metallb-deploy:
    #!/usr/bin/env bash
    set -e
    helmfile --file ./sys/metallb/helmfile.yaml apply
    kubectl apply -f ./sys/metallb/addresspool.yml

metallb-remove:
    #!/usr/bin/env bash
    helmfile --file ./sys/metallb/helmfile.yaml destroy || true
    kubectl delete -f ./sys/metallb/addresspool.yml || true
