---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/name: foundry-vtt
  name: foundry-vtt-data
spec:
  storageClassName: "" # needs to be blank so dynamic provisioners dont match
  capacity:
    storage: 10Gi # not enforced on NFS shares
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume2/kube-nfs/v/foundry-vtt-data # not dynamic so make sure it already exists on the NAS
    server: 192.168.1.200
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: foundry-vtt
  name: foundry-vtt-data
  namespace: foundry-vtt
spec:
  storageClassName: "" # needs to be blank so dynamic provisioners dont match
  volumeName: foundry-vtt-data
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
