resources:
  requests:
    memory: 30Mi
    cpu: 10m
  limits:
    memory: 64Mi

tolerations:
- key: "CriticalAddonsOnly"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: In
          values:
          - 'true'
