repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
helmDefaults:
  createNamespace: true
releases:
- name: odoo
  chart: bitnami/odoo
  namespace: erp
  values:
  # .gotmpl so we can resolve secrets from environment variables
  - ./helm-values.yml.gotmpl
