---
- name: reboot
  tags: [ reboot ]
  ansible.builtin.reboot:
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime

- name: reload-systemd
  ansible.builtin.systemd:
    daemon_reload: true