---
- name: reboot
  tags: [ sys-reboot ]
  ansible.builtin.reboot:
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime

- name: reload-systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart-k3s
  tags: [ k3s-reboot ]
  ansible.builtin.systemd:
      name: k3s
      state: restarted
  register: output
  failed_when:
    - output.failed == true
    - '"Could not find the requested service" not in output.msg'

- name: restart-sshd
  ansible.builtin.service:
    name: sshd
    state: restarted