---
# manually create a PV for config so we dont loose it when we update
# Need one per pod if running more than one replica, stateful sets should
# probably be used in that case
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/name: mealie
  name: mealie-data
spec:
  storageClassName: "" # needs to be blank so dynamic provisioners dont match
  capacity:
    storage: 10Gi # not enforced on NFS shares
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume2/kube-nfs/v/mealie-data #not dynamic so make sure it already exists on the NAS
    server: 192.168.1.200
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: mealie
  name: mealie-data
  namespace: mealie
spec:
  storageClassName: "" # needs to be blank so dynamic provisioners dont match
  volumeName: mealie-data
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
