server:
  retentionPeriod: 30d
  extraArgs:
    memory.allowedBytes: "200MB"
    search.maxUniqueTimeseries: "5000"
    inmemoryDataFlushInterval: "120s"
  persistentVolume:
    storageClassName: synology-nfs-app-data-retain
    size: 10Gi
  resources:
    requests:
      memory: 150Mi
      cpu: 100m
    limits:
      memory: 300Mi
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: In
            values:
            - 'true'

  scrape:
    enabled: true
    config:
      scrape_configs:
      - job_name: kube-state-metrics
        static_configs:
        - targets:
          - kube-state-metrics.obs.svc:8080
        scrape_interval: 60s

fullnameOverride: victoriametrics
