repositories:
- name: vm
  url: https://victoriametrics.github.io/helm-charts/
helmDefaults:
  createNamespace: true
releases:
- name: victoriametrics
  chart: vm/victoria-metrics-single
  version: 0.32.0
  namespace: obs
  values:
  - ./helm-values.yml
