repositories:
- name: k8s-at-home
  url: https://k8s-at-home.com/charts/
helmDefaults:
  createNamespace: true
releases:
- name: adguard-home
  chart: k8s-at-home/adguard-home
  namespace: adguard
  values:
  - ./helm-values.yml
