apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/version: 4.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  template:
    metadata:
      annotations:
        fluentbit.io/parser: "radarr"
      labels:
        app.kubernetes.io/name: radarr
    spec:
      terminationGracePeriodSeconds: 15

      # without this external DNS lookups fail with my setup (api.radarr.video => api.radarr.video.matthew-stratton.me)
      # https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html
      dnsConfig:
        options:
          - name: ndots
            value: "1"
            
      restartPolicy: Always
      volumes:
      - name: radarr-config
        persistentVolumeClaim:
          claimName: radarr-config
      - name: data
        nfs: # data folder is a mounted pre-existing NFS share, *not* a PV/PVC
          server: 192.168.1.200
          path: /volume1/Media
      containers:
      - env:
        - name: TZ
          value: America/New_York
        - name: PUID
          value: '222'
        - name: PGID
          value: '321'
        - name: UMASK
          value: '002'
        image: linuxserver/radarr:arm64v8-latest
        imagePullPolicy: IfNotPresent
        name: radarr
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 512Mi
        ports:
        - containerPort: 7878
          name: http
          protocol: TCP
        resources: {}
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /config
          name: radarr-config
