---
# manually create a PV for config so we dont loose it when we update
# Need one per pod if running more than one replica, stateful sets should
# probably be used in that case
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/name: radarr
  name: radarr-config
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 192.168.1.200:3260
    iqn: iqn.2000-01.com.synology:synology.default-target.7d1c64e1219
    lun: 3
    fsType: ext4
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: radarr
  name: radarr-config
  namespace: media
spec:
  storageClassName: "" # needs to be blank so dynamic provisioners dont match
  volumeName: radarr-config
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
