repositories:
- name: jetstack
  url: https://charts.jetstack.io
helmDefaults:
  createNamespace: true
releases:
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: v1.19.4
  values:
  - ./helm-values.yml
