repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts
helmDefaults:
  createNamespace: true
releases:
- name: grafana
  chart: grafana/grafana
  namespace: obs
  values:
  - ./helm-values.yml.gotmpl
