---
- name: Download k3s binary arm64
  get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s-arm64
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/sha256sum-arm64.txt
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
  tags: [ slow ]

- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes
  tags: [ slow ]

# https://github.com/k3s-io/k3s/issues/2400#issuecomment-1013798094
- name: Enable cgroup kill to make server shutdown faster
  systemd:
    name: cgroup-kill-on-shutdown@k3s.service.service
    daemon_reload: yes
    enabled: yes
