---
# It is a bit awkward to get the agent-token file, which is generated on first `k3s server` startup, 
# from the master node. role/k3s/master executes first, waits for the file to exist and then uses 
# ansible.builtin.set_fact to store the file contents for role/k3s/node to use.
- name: ensure agent-token file exists
  ansible.builtin.copy:
    dest: /var/lib/rancher/k3s/agent/agent-token
    content: "{{ hostvars[groups['master'][0]]['agent_token'] }}"
  notify: restart-k3s

- name: Deploy systemd unit files
  tags: [ slow, k3s-reboot ]
  ansible.builtin.template:
    src: k3s.service
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: 0644
  notify: 
    - reload-systemd
    - restart-k3s

- name: Enable and check K3s service
  tags: [ slow, k3s-reboot ]
  systemd:
    name: k3s
    daemon_reload: yes
    state: "started"
    enabled: yes
  notify: restart-k3s