# https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
.tolerate-control-plane: &tolerate-control-plane
  key: "CriticalAddonsOnly"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"

controller:
  terminationGracePeriodSeconds: 30
  tolerations:
  - <<: *tolerate-control-plane

  admissionWebhooks:
    patch:
      tolerations:
      - <<: *tolerate-control-plane
  config:
    use-gzip: "true"
  extraArgs:
    enable-ssl-passthrough: true

  name: controller-internal

  hostname: nginx-internal-lb
  ingressClass: nginx-internal
  electionID: nginx-internal-leader
  ingressClassResource:
    name: nginx-internal
    enabled: true
    default: false
    controllerValue: "k8s.io/ingress-nginx-internal"

  service:
    annotations:
      metallb.io/loadBalancerIPs: "192.168.1.221"
    external:
      enabled: true

