resources:
  requests:
    memory: 50Mi
    cpu: 50m
  limits:
    memory: 150Mi

tolerations:
- key: "CriticalAddonsOnly"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"

config:
  agent:
    interval: "60s"
    round_interval: true
    metric_batch_size: 200
    metric_buffer_limit: 1000
    collection_jitter: "0s"
    flush_interval: "60s"
    flush_jitter: "5s"
    hostname: "$HOSTNAME"
    omit_hostname: false
  inputs:
    - cpu:
        percpu: false
        totalcpu: true
        collect_cpu_time: false
        report_active: false
    - mem:
        fieldinclude: ["available", "available_percent", "buffered", "cached", "free", "swap_free", "swap_total", "total", "used", "used_percent"]
    - disk:
        mount_points: ["/", "/boot"]
        ignore_fs:
          - tmpfs
          - devtmpfs
          - devfs
          - iso9660
          - overlay
          - aufs
          - squashfs
        fieldinclude: ["free", "total", "used", "used_percent"]
    - diskio:
        fieldinclude: ["io_time", "read_bytes", "write_bytes", "reads", "writes", "io_await", "weighted_io_time"]
        log_level: "error"
    - net:
        fieldinclude: ["bytes_recv", "bytes_sent", "drop_in", "drop_out", "err_in", "err_out"]
    - system:
        fieldinclude: ["uptime", "load1", "load5", "load15", "n_cpus"]
    - processes:
        fieldinclude: ["blocked", "running", "total", "total_threads", "zombies"]
    - temp: {}
    - kubernetes:
        url: "https://$HOSTIP:10250"
        bearer_token: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        insecure_skip_verify: true
        fieldinclude: ["cpu_usage_nanocores", "memory_working_set_bytes", "rx_bytes", "tx_bytes"]
  outputs:
    - influxdb_v2:
        urls:
          - "http://victoriametrics-server.obs.svc:8428"
        token: "none"
        organization: "none"
        bucket: "none"
