repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
helmDefaults:
  createNamespace: true
releases:
- name: kps
  chart: prometheus-community/kube-prometheus-stack
  namespace: obs
  values:
  - ./helm-values.yml.gotmpl
