repositories:
- name: influxdata
  url: https://helm.influxdata.com/
helmDefaults:
  createNamespace: true
releases:
- name: telegraf-snmp
  chart: influxdata/telegraf
  version: 1.8.67
  namespace: obs
  values:
  - ./helm-values.yml.gotmpl
