---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/name: jellyfin
  name: jellyfin-config
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 192.168.1.200:3260
    iqn: iqn.2000-01.com.synology:synology.default-target.7d1c64e1219
    lun: 1
    fsType: ext4
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: jellyfin
  name: jellyfin-config
  namespace: media
spec:
  storageClassName: "" # needs to be blank so dynamic provisioners dont match
  volumeName: jellyfin-config
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# node local storage for cache/transcode speed. not guaranteed to 
# survive long term but realistically should exist until explicitly 
# deleted or the OS is reinstalled
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: jellyfin
  name: jellyfin-volitile
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem