---

- name: "Install storage packages"
  package:
    name:
    - "open-iscsi"
    - "lsscsi"
    - "sg3-utils"
    - "multipath-tools"
    - "scsitools"
    - "nfs-common"
    state: 'present'
  tags: [ slow ]

- name: Configure iscsi multipath
  template:
    src: multipath.conf.j2
    dest: /etc/multipath.conf
    owner: root
    group: root
    mode: 0755

- name: Configure iscsi initiatorname
  template:
    src: initiatorname.iscsi.j2
    dest: /etc/iscsi/initiatorname.iscsi
    owner: 'root'
    group: 'root'
    mode: '0600'

# disable iscsi for now since its crazy slow on boot
# change to automatic to turn back on
- name: Set startup to manual in /etc/iscsi/iscsid.conf
  lineinfile:
    path: '/etc/iscsi/iscsid.conf'
    regex: '^node\.startup\ =\ automatic'
    line: 'node.startup = manual'
    owner: 'root'
    group: 'root'
    mode: '0600'

# change to enabled: true/state: started to turn back on
- name: Manage iscsi services
  systemd:
    name: "{{ item.name }}"
    state: stopped
    enabled: no
  loop:
    - { name: 'iscsid' }
    - { name: 'open-iscsi' }
    - { name: 'multipath-tools' }
