---
- name: configure boot options
  template:
    src: usercfg.txt.j2
    dest: /boot/firmware/usercfg.txt
    owner: root
    group: root
    mode: 0755
  notify: reboot

- name: set locale
  command: /usr/sbin/update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

- name: set /etc/localtime
  file: src=/usr/share/zoneinfo/America/New_York dest=/etc/localtime state=link

- name: Set timezone variables
  copy:
    content: 'America/New_York'
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: update timezone

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  tags: [ slow ]

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes
  tags: [ slow ]

- name: changing hostname
  hostname: name="{{ inventory_hostname }}"
  register: "hostname_status"
  become: true
  when: ansible_fqdn != ansible_ssh_host
  notify: reboot

- name: change /etc/hosts to remove old hostname
  become: true
  lineinfile:
    state: present
    path: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}"
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
  when: ansible_fqdn != inventory_hostname

- name: Add kubeinfo to motd
  template:
    src: 60-kubeinfo.j2
    dest: /etc/update-motd.d/60-kubeinfo
    owner: root
    group: root
    mode: 0755

# Hardware watchdog should be enabled by default on rpi 3+ so you shouldnt need
# to enable it with modprobe or dtparam in /boot/config.txt
# Useful links:
#   https://raspberrypi.stackexchange.com/questions/108080/watchdog-on-the-rpi4
#   https://forums.raspberrypi.com/viewtopic.php?f=29&t=147501
- name: configure systemd hardware watchdog
  template:
    src: system.conf.j2
    dest: /etc/systemd/system.conf
    owner: root
    group: root
    mode: 0644
  notify: reboot

- name: Copy resolv.conf for my network
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644

- name: Check if a reboot is needed for Debian and Ubuntu boxes
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=no
  notify: reboot
