---
- name: set locale
  command: /usr/sbin/update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

- name: set /etc/localtime
  file: src=/usr/share/zoneinfo/America/New_York dest=/etc/localtime state=link

- name: Set timezone variables
  copy:
    content: 'America/New_York'
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: update timezone

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes

- name: changing hostname
  hostname: name="{{ inventory_hostname }}"
  register: "hostname_status"
  become: true
  when: ansible_fqdn != ansible_ssh_host
  notify: reboot

- name: change /etc/hosts to remove old hostname
  become: true
  lineinfile:
    state: present
    path: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}"
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
  when: ansible_fqdn != inventory_hostname

- name: disable motd-news
  become: true
  lineinfile:
    path: /etc/default/motd-news
    regexp: '^ENABLED='
    line: ENABLED=0

- name: Add kubeinfo to motd
  template:
    src: 60-kubeinfo.j2
    dest: /etc/update-motd.d/60-kubeinfo
    owner: root
    group: root
    mode: 0755

- name: remove Ubuntu motd-help
  ansible.builtin.file:
    path: /etc/update-motd.d/10-help-text
    state: absent

- name: Check if a reboot is needed for Debian and Ubuntu boxes
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=no
  notify: reboot

- name: Copy resolv.conf for my network
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644

- name: Stop and disable systemd-resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
