apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: qbittorrent
  name: qbittorrent-config
  namespace: arr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: synology-nfs-app-data-delete
  volumeMode: Filesystem
