apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: arr
  labels:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/version: 3.0.8
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
  template:
    metadata:
      annotations:
        fluentbit.io/parser: "sonarr"
      labels:
        app.kubernetes.io/name: sonarr
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - name: sonarr-config
        persistentVolumeClaim:
          claimName: sonarr-config
      - name: data
        nfs: # data folder is a mounted pre-existing NFS share, *not* a PV/PVC
          server: 192.168.1.200
          path: /volume1/Media
      containers:
      - env:
        - name: TZ
          value: America/New_York
        - name: PUID
          value: '333'
        - name: PGID
          value: '321'
        - name: UMASK
          value: '002'
        image: lscr.io/linuxserver/sonarr:3.0.8
        imagePullPolicy: IfNotPresent
        name: sonarr
        resources:
          requests:
            memory: 128Mi
          limits:
            memory: 512Mi
        ports:
        - containerPort: 8989
          name: http
          protocol: TCP
        resources: {}
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /config
          name: sonarr-config
